---
- name: install s/w apps
  hosts: all
  tasks: 
    - name: installl git softwear
      apt:  
        name: "{{item}}"
        state: present
        update_cache: no
      with_items:
         - tree
         - git
         - maven

...          
