---
- name: install s/w's
  hosts: all
  serial: 1
  tasks:
    - name: install reqiured softwears
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
        purge: yes
      with_items:
         - git
         - maven
         - tomcat9
         - tomcat9-admin
         - tree    
    
