---
- name: create  file based on  a condition
  hosts: all
  vars:
    - a: 10
  tasks:
    - name: create  a file
      file:
        name: /tmp/file4
        state: touch
      when: a == 10    


