---
- name: implementing docker composing using ansible
  hosts: all
  tasks:
    - name: creat  mysql container
      docker_container:
        name: mydb
        image: mysql
        env: 
          MYSQL_ROOT_PASSWORD: ramesh

    - name: creat a wordpress container
      docker_container:
        name: mywordpress
        image: wordpress
        ports:
            - 8888:80
        links:
            - mydb:mysql      

