---
- name : create user
  hosts : all
  serial: 1
  tasks :
    - name : user creation
      user :
        name : anu
        password : 1234
        uid : 3232
        home : /home/anu
        comment : "a normal  user"
        shell : /bin/bash

...        

