- name: install s/w apps
  hosts: all
  tasks:
    - name: install s/w's
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
         - {a: tree,b: absent,c: no}
...


