---
- name: create 10 nginx containers for load balancer
  hosts: all
  tasks:
     - name: create 10 nginx containers
       docker_container: 
           name: "container{{item}}"
           image: nginx
       loop: "{{[0,4,7,9]}}"      
