---
- name: error handling
  hosts: all
  tasks:
    - block: 
       - name: install tree usinng apt
         apt:
           name: tree
           state: present
           update_cache: yes
      rescue:
       - name: install tree using yum
         yum:  
           name: tree
           state: present
           update_cache: yes
      always:
        - name: disply  success lines
          debug:
            msg: "tree  installation successful"

...             
