---
- name: install firewall using host scope variabls
  hosts: webserver
  tasks: 
   - name: install firewalld  
     apt: 
       name: "{{a}}"
       state: "{{b}}"
       update_cache: "{{c}}"
...        
